Add progress to register file.
Todo, the repr isn't working due to some type error

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_9970/1618180387.py in <module>
      1 r = RegisterFile()
      2 r.switch_display()
----> 3 print(r)

/tmp/ipykernel_9970/78077914.py in __repr__(self)
     90         if (self.fullreg == True):
     91             for l in range(32):
---> 92                 data = self.regfile[l].data()
     93                 if (data is None):
     94                     data = "xxxxxxxx"

TypeError: 'int' object is not callable